## Web-Scraping Code for NBA Players Stats Last 10 Seasons from NBA.COM

In [3]:
import pandas as pd 
import requests
import numpy as np
pd.set_option('display.max_columns', None)

In [4]:
season_types = ['Regular%20Season', 'Playoffs']
years = ['2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21','2021-22','2022-23','2023-24']

In [5]:
headers_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2013-14&SeasonType=Regular+Season&StatCategory=PTS'

In [6]:
r = requests.get(url=headers_url).json()
table_headers = r['resultSet']['headers']

In [22]:
data_columns = ['Year','Season_type'] + table_headers
df = pd.DataFrame(columns=data_columns)

for y in years:
    for t in season_types:
        api_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season='+y+'&SeasonType='+t+'&StatCategory=PTS'
        r = requests.get(url=api_url).json()
        temp1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)
        temp2 = pd.DataFrame({'Year':[y for i in range(len(temp1))],
                         'Season_type':[t for i in range(len(temp1))]})
        temp3 = pd.concat([temp2,temp1], axis=1)
        df = pd.concat([df, temp3], axis=0)
        print(f'Finished Data Scraping for The {y} {t}.') 

df.to_csv('NBA_Players_Stats.csv')
print('Data Scraping is Finished and The CSV File is Ready')

Finished Data Scraping for The 2013-14 Regular%20Season.
Finished Data Scraping for The 2013-14 Playoffs.
Finished Data Scraping for The 2014-15 Regular%20Season.
Finished Data Scraping for The 2014-15 Playoffs.
Finished Data Scraping for The 2015-16 Regular%20Season.
Finished Data Scraping for The 2015-16 Playoffs.
Finished Data Scraping for The 2016-17 Regular%20Season.
Finished Data Scraping for The 2016-17 Playoffs.
Finished Data Scraping for The 2017-18 Regular%20Season.
Finished Data Scraping for The 2017-18 Playoffs.
Finished Data Scraping for The 2018-19 Regular%20Season.
Finished Data Scraping for The 2018-19 Playoffs.
Finished Data Scraping for The 2019-20 Regular%20Season.
Finished Data Scraping for The 2019-20 Playoffs.
Finished Data Scraping for The 2020-21 Regular%20Season.
Finished Data Scraping for The 2020-21 Playoffs.
Finished Data Scraping for The 2021-22 Regular%20Season.
Finished Data Scraping for The 2021-22 Playoffs.
Finished Data Scraping for The 2022-23 Regular%20Season.
Finished Data Scraping for The 2022-23 Playoffs.
Finished Data Scraping for The 2023-24 Regular%20Season.
Finished Data Scraping for The 2023-24 Playoffs.
Data Scraping is Finished and The CSV File is Ready

In [17]:
df.shape

(8158, 30)

In [18]:
df.head()

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2013-14,Regular%20Season,201142,1,Kevin Durant,1610612760,OKC,81,3122,849,1688,0.503,192,491,0.391,703,805,0.873,58,540,598,445,103,59,285,174,2593,2572,1.56,0.36
1,2013-14,Regular%20Season,2546,2,Carmelo Anthony,1610612752,NYK,77,2982,743,1643,0.452,167,415,0.402,459,541,0.848,145,477,622,242,95,51,198,224,2112,1942,1.22,0.48
2,2013-14,Regular%20Season,2544,3,LeBron James,1610612748,MIA,77,2902,767,1353,0.567,116,306,0.379,439,585,0.750,81,452,533,488,121,26,270,126,2089,2255,1.81,0.45
3,2013-14,Regular%20Season,201567,4,Kevin Love,1610612750,MIN,77,2797,650,1421,0.457,190,505,0.376,520,633,0.821,224,739,963,341,59,35,196,136,2010,2328,1.74,0.30
4,2013-14,Regular%20Season,201933,5,Blake Griffin,1610612746,LAC,80,2863,718,1359,0.528,12,44,0.273,482,674,0.715,192,565,757,309,92,51,224,265,1930,2082,1.38,0.41

In [19]:
df.tail()

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
209,2023-24,Playoffs,1641765,198,Olivier-Maxence Prosper,1610612742,DAL,3,9,0,2,0.0,0,0,0.0,0,0,0.0,0,3,3,1,0,0,0,0,0,2,0.0,0.0
210,2023-24,Playoffs,1631115,198,Orlando Robinson,1610612748,MIA,1,2,0,1,0.0,0,1,0.0,0,0,0.0,0,1,1,1,0,0,0,0,0,1,0.0,0.0
211,2023-24,Playoffs,203933,198,T.J. Warren,1610612750,MIN,3,11,0,2,0.0,0,1,0.0,0,0,0.0,2,1,3,1,0,0,0,0,0,2,0.0,0.0
212,2023-24,Playoffs,201152,198,Thaddeus Young,1610612756,PHX,1,4,0,0,0.0,0,0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0.0,0.0
213,2023-24,Playoffs,203648,198,Thanasis Antetokounmpo,1610612749,MIL,2,5,0,0,0.0,0,0,0.0,0,0,0.0,0,0,0,0,1,1,0,1,0,2,0.0,0.0

In [20]:
df.duplicated().sum()

0

In [21]:
df.isna().sum()

Year           0
Season_type    0
PLAYER_ID      0
RANK           0
PLAYER         0
TEAM_ID        0
TEAM           0
GP             0
MIN            0
FGM            0
FGA            0
FG_PCT         0
FG3M           0
FG3A           0
FG3_PCT        0
FTM            0
FTA            0
FT_PCT         0
OREB           0
DREB           0
REB            0
AST            0
STL            0
BLK            0
TOV            0
PF             0
PTS            0
EFF            0
AST_TOV        0
STL_TOV        0
dtype: int64